[package]
name = "ic10lsp_wasm"
version.workspace = true
edition.workspace = true

# [features]
# default = ["tower-lsp/runtime-agnostic"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
futures = "0.3.30"
js-sys = "0.3.69"
web-sys = { version = "0.3.69", features = ["WritableStream", "console"] }
tokio = { version = "1.37.0", features = ["sync"] }
tower-lsp = { version = "0.20.0", default-features = false, features = [
    "runtime-agnostic",
] }
# tree-sitter = { version = "0.9.0", package = "tree-sitter-facade" }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = { version = "0.4.42", features = [
    "futures-core-03-stream",
] }
wasm-streams = "0.4"
# web-tree-sitter-sys = "1.3"
ic10lsp = { git = "https://github.com/Ryex/ic10lsp.git", branch = "wasm" }
# ic10lsp = { path = "../../ic10lsp" }
