// =================================================
//   !! <----->      DO NOT MODIFY      <-----> !!
//
//   This module was automatically generated by an
//   xtask
//
//   run
//
//   `cargo xtask generate -m database` 
//
//   from the workspace to regenerate
//
// =================================================

use crate::templates::Reagent;
pub fn build_reagent_database() -> std::collections::BTreeMap<
    u8,
    crate::templates::Reagent,
> {
    #[allow(clippy::unreadable_literal)]
    let mut map: std::collections::BTreeMap<u8, crate::templates::Reagent> = std::collections::BTreeMap::new();
    map.insert(
        20u8,
        Reagent {
            id: 20u8,
            name: "Alcohol".into(),
            hash: 1565803737i32,
            unit: "ml".into(),
            is_organic: true,
            sources: vec![].into_iter().collect(),
        },
    );
    map.insert(
        36u8,
        Reagent {
            id: 36u8,
            name: "Astroloy".into(),
            hash: -1493155787i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemAstroloyIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        40u8,
        Reagent {
            id: 40u8,
            name: "Biomass".into(),
            hash: 925270362i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![("ItemBiomass".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        5u8,
        Reagent {
            id: 5u8,
            name: "Carbon".into(),
            hash: 1582746610i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("HumanSkull".into(), 1f64), ("ItemCharcoal".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        37u8,
        Reagent {
            id: 37u8,
            name: "Cobalt".into(),
            hash: 1702246124i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemCobaltOre".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        44u8,
        Reagent {
            id: 44u8,
            name: "Cocoa".into(),
            hash: 678781198i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![
                ("ItemCocoaPowder".into(), 1f64), ("ItemCocoaTree".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        27u8,
        Reagent {
            id: 27u8,
            name: "ColorBlue".into(),
            hash: 557517660i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ReagentColorBlue".into(), 10f64)].into_iter().collect(),
        },
    );
    map.insert(
        26u8,
        Reagent {
            id: 26u8,
            name: "ColorGreen".into(),
            hash: 2129955242i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ReagentColorGreen".into(), 10f64)].into_iter().collect(),
        },
    );
    map.insert(
        29u8,
        Reagent {
            id: 29u8,
            name: "ColorOrange".into(),
            hash: 1728153015i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ReagentColorOrange".into(), 10f64)].into_iter().collect(),
        },
    );
    map.insert(
        25u8,
        Reagent {
            id: 25u8,
            name: "ColorRed".into(),
            hash: 667001276i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ReagentColorRed".into(), 10f64)].into_iter().collect(),
        },
    );
    map.insert(
        28u8,
        Reagent {
            id: 28u8,
            name: "ColorYellow".into(),
            hash: -1430202288i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ReagentColorYellow".into(), 10f64)].into_iter().collect(),
        },
    );
    map.insert(
        15u8,
        Reagent {
            id: 15u8,
            name: "Constantan".into(),
            hash: 1731241392i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemConstantanIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        7u8,
        Reagent {
            id: 7u8,
            name: "Copper".into(),
            hash: -1172078909i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![
                ("ItemCopperIngot".into(), 1f64), ("ItemCopperOre".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        38u8,
        Reagent {
            id: 38u8,
            name: "Corn".into(),
            hash: 1550709753i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![("ItemCookedCorn".into(), 1f64), ("ItemCorn".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        2u8,
        Reagent {
            id: 2u8,
            name: "Egg".into(),
            hash: 1887084450i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![
                ("ItemCookedPowderedEggs".into(), 1f64), ("ItemEgg".into(), 1f64),
                ("ItemFertilizedEgg".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        13u8,
        Reagent {
            id: 13u8,
            name: "Electrum".into(),
            hash: 478264742i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemElectrumIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        24u8,
        Reagent {
            id: 24u8,
            name: "Fenoxitone".into(),
            hash: -865687737i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemFern".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        0u8,
        Reagent {
            id: 0u8,
            name: "Flour".into(),
            hash: -811006991i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemFlour".into(), 50f64)].into_iter().collect(),
        },
    );
    map.insert(
        4u8,
        Reagent {
            id: 4u8,
            name: "Gold".into(),
            hash: -409226641i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemGoldIngot".into(), 1f64), ("ItemGoldOre".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        35u8,
        Reagent {
            id: 35u8,
            name: "Hastelloy".into(),
            hash: 2019732679i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemHastelloyIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        9u8,
        Reagent {
            id: 9u8,
            name: "Hydrocarbon".into(),
            hash: 2003628602i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemCoalOre".into(), 1f64), ("ItemSolidFuel".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        34u8,
        Reagent {
            id: 34u8,
            name: "Inconel".into(),
            hash: -586072179i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemInconelIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        14u8,
        Reagent {
            id: 14u8,
            name: "Invar".into(),
            hash: -626453759i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemInvarIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        3u8,
        Reagent {
            id: 3u8,
            name: "Iron".into(),
            hash: -666742878i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemIronIngot".into(), 1f64), ("ItemIronOre".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        12u8,
        Reagent {
            id: 12u8,
            name: "Lead".into(),
            hash: -2002530571i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemLeadIngot".into(), 1f64), ("ItemLeadOre".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        1u8,
        Reagent {
            id: 1u8,
            name: "Milk".into(),
            hash: 471085864i32,
            unit: "ml".into(),
            is_organic: true,
            sources: vec![
                ("ItemCookedCondensedMilk".into(), 1f64), ("ItemMilk".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        42u8,
        Reagent {
            id: 42u8,
            name: "Mushroom".into(),
            hash: 516242109i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![
                ("ItemCookedMushroom".into(), 1f64), ("ItemMushroom".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        11u8,
        Reagent {
            id: 11u8,
            name: "Nickel".into(),
            hash: 556601662i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![
                ("ItemNickelIngot".into(), 1f64), ("ItemNickelOre".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        21u8,
        Reagent {
            id: 21u8,
            name: "Oil".into(),
            hash: 1958538866i32,
            unit: "ml".into(),
            is_organic: true,
            sources: vec![("ItemSoyOil".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        17u8,
        Reagent {
            id: 17u8,
            name: "Plastic".into(),
            hash: 791382247i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![].into_iter().collect(),
        },
    );
    map.insert(
        22u8,
        Reagent {
            id: 22u8,
            name: "Potato".into(),
            hash: -1657266385i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![("ItemPotato".into(), 1f64), ("ItemPotatoBaked".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        30u8,
        Reagent {
            id: 30u8,
            name: "Pumpkin".into(),
            hash: -1250164309i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![
                ("ItemCookedPumpkin".into(), 1f64), ("ItemPumpkin".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        31u8,
        Reagent {
            id: 31u8,
            name: "Rice".into(),
            hash: 1951286569i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemCookedRice".into(), 1f64), ("ItemRice".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        19u8,
        Reagent {
            id: 19u8,
            name: "SalicylicAcid".into(),
            hash: -2086114347i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![].into_iter().collect(),
        },
    );
    map.insert(
        18u8,
        Reagent {
            id: 18u8,
            name: "Silicon".into(),
            hash: -1195893171i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![
                ("ItemSiliconIngot".into(), 0.1f64), ("ItemSiliconOre".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        10u8,
        Reagent {
            id: 10u8,
            name: "Silver".into(),
            hash: 687283565i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![
                ("ItemSilverIngot".into(), 1f64), ("ItemSilverOre".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        16u8,
        Reagent {
            id: 16u8,
            name: "Solder".into(),
            hash: -1206542381i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemSolderIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        41u8,
        Reagent {
            id: 41u8,
            name: "Soy".into(),
            hash: 1510471435i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![
                ("ItemCookedSoybean".into(), 1f64), ("ItemSoybean".into(), 1f64)
            ]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        8u8,
        Reagent {
            id: 8u8,
            name: "Steel".into(),
            hash: 1331613335i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemEmptyCan".into(), 1f64), ("ItemSteelIngot".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        33u8,
        Reagent {
            id: 33u8,
            name: "Stellite".into(),
            hash: -500544800i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemStelliteIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        43u8,
        Reagent {
            id: 43u8,
            name: "Sugar".into(),
            hash: 1778746875i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemSugar".into(), 10f64), ("ItemSugarCane".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        23u8,
        Reagent {
            id: 23u8,
            name: "Tomato".into(),
            hash: 733496620i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![("ItemCookedTomato".into(), 1f64), ("ItemTomato".into(), 1f64)]
                .into_iter()
                .collect(),
        },
    );
    map.insert(
        6u8,
        Reagent {
            id: 6u8,
            name: "Uranium".into(),
            hash: -208860272i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemUraniumOre".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        32u8,
        Reagent {
            id: 32u8,
            name: "Waspaloy".into(),
            hash: 1787814293i32,
            unit: "g".into(),
            is_organic: true,
            sources: vec![("ItemWaspaloyIngot".into(), 1f64)].into_iter().collect(),
        },
    );
    map.insert(
        39u8,
        Reagent {
            id: 39u8,
            name: "Wheat".into(),
            hash: -686695134i32,
            unit: "".into(),
            is_organic: true,
            sources: vec![("ItemWheat".into(), 1f64)].into_iter().collect(),
        },
    );
    map
}
