[package]
name = "ic10emu_frontend"
version = "0.1.0"
authors = ["Rachel Powers <508861+Ryex@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.0-rc.3", features = [] }
serde = "=1.0.219" # higher is incompatable with libsql-client
serde_with = "=3.14.0"
libsql-client = { version = "0.33.4", default-features = false, features = ["reqwest_backend"] }
tracing = "0.1.41"
tracing-wasm = "0.2.1"
url = "2.5.7"
uuid = { version = "1.18.1", features = ["js", "v4", "v5", "v7", "v8"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
gloo-utils = "0.2.0"
strum = { version = "0.27.2", features = ["derive"] }
indoc = "2.0.7"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[build-dependencies]
build-data = "0.3.3"
dotenv = "0.15.0"
