use color_eyre::eyre::{self, Context};
use quote::ToTokens;

use std::collections::BTreeMap;

use crate::{enums::Enums, stationpedia::Stationpedia};

mod database;
mod enums;
mod highlight_rules;
mod instructions;
mod utils;

pub fn generate(
    stationpedia_path: &std::path::Path,
    workspace: &std::path::Path,
    modules: &[&str],
) -> color_eyre::Result<()> {
    let mut pedia: Stationpedia = parse_json(&mut serde_json::Deserializer::from_reader(
        std::io::BufReader::new(std::fs::File::open(
            stationpedia_path.join("Stationpedia.json"),
        )?),
    ))?;

    let instruction_help_patches: BTreeMap<String, String> = parse_json(
        &mut serde_json::Deserializer::from_reader(std::io::BufReader::new(std::fs::File::open(
            workspace.join("data").join("instruction_help_patches.json"),
        )?)),
    )?;

    for (inst, patch) in instruction_help_patches {
        if let Some(cmd) = pedia.script_commands.get_mut(&inst) {
            cmd.desc = patch;
        } else {
            tracing::warn!("Can't find instruction '{inst}' to patch help!");
        }
    }

    let enums: Enums = parse_json(&mut serde_json::Deserializer::from_reader(
        std::io::BufReader::new(std::fs::File::open(stationpedia_path.join("Enums.json"))?),
    ))?;

    let mut generated_files = Vec::new();
    if modules.contains(&"enums") {
        if modules.len() > 1 {
            tracing::warn!(
                "generating enums alone, recompile the xtask and run again with other modules."
            )
        } else {
            tracing::info!("generating enums...");
        }

        let enums_files = enums::generate(&pedia, &enums, workspace)?;
        tracing::info!("Formatting generated files...");
        for (file, format) in &enums_files {
            prepend_generated_comment_and_format(file, "enums", *format)?;
        }
        return Ok(());
    }

    if modules.contains(&"database") {
        tracing::info!("generating database...");

        let database_files = database::generate_database(&pedia, &enums, workspace)?;
        generated_files.extend(database_files.into_iter().map(|(path, format)| (path, format, "database")));
    }

    if modules.contains(&"instructions") {
        tracing::info!("generating instructions...");
        let inst_files = instructions::generate_instructions(&pedia, workspace)?;
        generated_files.extend(inst_files.into_iter().map(|(path, format)| (path, format, "instructions")));
    }

    if modules.contains(&"hl_rules") {
        tracing::info!("generating Ace highlight rules...");
        let hlrules_files = highlight_rules::generate(&pedia, &enums, workspace)?;
        generated_files.extend(hlrules_files.into_iter().map(|(path, format)| (path, format, "hl_rules")));
    }

    tracing::info!("Formatting generated files...");
    for (file, format, module) in &generated_files {
        prepend_generated_comment_and_format(file, module, *format)?;
    }
    Ok(())
}

pub fn parse_json<'a, T: serde::Deserialize<'a>>(
    jd: impl serde::Deserializer<'a>,
) -> Result<T, color_eyre::Report> {
    let mut track = serde_path_to_error::Track::new();
    let path = serde_path_to_error::Deserializer::new(jd, &mut track);
    let mut fun = |path: serde_ignored::Path| {
        tracing::warn!(key=%path,"Found ignored key");
    };
    serde_ignored::deserialize(path, &mut fun).map_err(|e| {
        eyre::eyre!(
            "path: {track} | error = {e}",
            track = track.path().to_string(),
        )
    })
}

fn format_rust(content: impl ToTokens) -> color_eyre::Result<String> {
    let content = syn::parse2(content.to_token_stream())?;
    Ok(prettyplease::unparse(&content))
}

fn prepend_generated_comment_and_format(
    file_path: &std::path::Path,
    module: &str,
    format: bool,
) -> color_eyre::Result<()> {
    use std::io::Write;
    let tmp_path = file_path.with_extension("rs.tmp");
    {
        let mut tmp = std::fs::File::create(&tmp_path)?;
        let content = std::fs::read_to_string(file_path)?;
        let src = if format {
            let src = syn::parse_file(&content)
                .with_context(|| format!("Error parsing file {}", file_path.display()))?;
            format_rust(src)?
        } else {
            content
        };

        write!(
            &mut tmp,
            "\
            // =================================================\n\
            //   !! <----->      DO NOT MODIFY      <-----> !!\n\
            //\n\
            //   This module was automatically generated by an\n\
            //   xtask\n\
            //\n\
            //   run\n\
            //\n\
            //   `cargo xtask generate -m {module}` \n\
            //\n\
            //   from the workspace to regenerate\n\
            //\n\
            // =================================================\n\
            \n\
            {src}\
            "
        )?;
    }
    std::fs::remove_file(file_path)?;
    std::fs::rename(&tmp_path, file_path)?;
    Ok(())
}
